### PR TITLE
PMU button fix

### PR DESCRIPTION
**Pull request by odudex**
was wrong but not causing issues

### CODE REVIEW

**Comment by tadeubas** [comment]
You could test this change on m5stickv? If yes, then I think it can be merged

**Comment by odudex** [comment]
Yes, I tested it. I didn't merge it to main yet because I was concerned about reproducibility of recent release. As it wasn't causing issues I thought to do it for next release.

**Comment by jreesun** [comment]
> Yes, I tested it. I didn't merge it to main yet because I was concerned about reproducibility of recent release. As it wasn't causing issues I thought to do it for next release.

Something to keep in mind for future releases:
In the `krux` repo if you're careful to checkout a specific commit of MaixPy in the submodule and commit it (to the krux repo), then future commits to the `master` branch of MaixPy here will not affect reproducibility since the submodule should always pin to the particular commit you checked out.

Hope that makes sense!

**Comment by odudex** [comment]
> Something to keep in mind for future releases: In the `krux` repo if you're careful to checkout a specific commit of MaixPy in the submodule and commit it (to the krux repo), then future commits to the `master` branch of MaixPy here will not affect reproducibility since the submodule should always pin to the particular commit you checked out.

Ok, I will merge this PR then!

**Pull request merged**
